import Link from "next/link";
import "@catppuccin/tailwindcss";
import "./globals.css";
import localFont from "next/font/local";
import { Analytics } from "@/components/analytics";
import LayoutWrapper from "../components/LayoutWrapper";
import { RootLayoutProviders } from "./providers";

const gilroy = localFont({
  src: [
    {
      path: "../public/Fonts/Gilroy-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/Fonts/Gilroy-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/Fonts/Gilroy-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-gilroy",
});

const helv = localFont({
  src: [
    {
      path: "../public/Fonts/HelveticaNowText-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/Fonts/HelveticaNowText-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-helv",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${gilroy.variable} ${helv.variable} ctp-latte bg-ctp-base text-ctp-text dark:ctp-mocha`}
      >
        <RootLayoutProviders>
          <LayoutWrapper>{children}</LayoutWrapper>
        </RootLayoutProviders>
      </body>
    </html>
  );
}
